[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"
[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-store"
